[[main]]
    identifier = "home"
    name       = "主页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 2
    [main.params]
        icon = "user"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 3
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 4
    [main.params]
        icon = "search"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "/contact/mail/"
    weight     = 1
    [social.params]
        icon = "mail"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/lgtlgt0015-code"
    weight     = 2
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "qq"
    name       = "QQ"
    url        = "/contact/qq/"
    weight     = 3
    [social.params]
        icon = "qq"

[[social]]
    identifier = "x"
    name       = "X (Twitter)"
    url        = "https://x.com/diknow_tik"
    weight     = 4
    [social.params]
        icon = "brand-x"
