[[main]]
    identifier = "home"
    name       = "主页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 2
    [main.params]
        icon = "user"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 3
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 4
    [main.params]
        icon = "search"

[[social]]
    name       = "Email"
    url        = "mailto:your-email@example.com"
    weight     = 1
    [social.params]
        icon = "mail"

[[social]]
    name       = "GitHub"
    url        = "https://github.com/your-username"
    weight     = 2
    [social.params]
        icon = "brand-github"

[[social]]
    name       = "Telegram"
    url        = "https://t.me/your-username"
    weight     = 3
    [social.params]
        icon = "telegram"

[[social]]
    name       = "Twitter"
    url        = "https://twitter.com/your-username"
    weight     = 4
    [social.params]
        icon = "brand-twitter"
