mainSections   = ["post"]
rssFullContent = true
SortBy         = "default"

[footer]
    since = 2026

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    compact  = false
    emoji    = "🎮"
    subtitle = "GalGame 攻略 · 评测 · 资源"
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    toc           = true
    readingTime   = true

    [article.list]
        showTags = true

    [article.license]
        enabled = false

[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"
    [widgets.homepage.params]
        limit = 5

[[widgets.homepage]]
    type = "categories"
    [widgets.homepage.params]
        limit = 10

[[widgets.homepage]]
    type = "tag-cloud"
    [widgets.homepage.params]
        limit = 15

[[widgets.page]]
    type = "toc"

[comments]
    enabled  = false

[cookies]
    enabled = false

[colorScheme]
    toggle  = true
    default = "dark"
